name: Run PHP Tests with PHPUnit

on: 
  push:
    branches:
      - main  # รันทดสอบเมื่อ push ไปที่ branch main
  pull_request:  # รันทดสอบเมื่อมี pull request
    branches:
      - main  # รันทดสอบเมื่อมี pull request มาที่ branch main

jobs:
  test:
    runs-on: ubuntu-latest  # รันบนระบบปฏิบัติการ Ubuntu

    services:
      mysql:  # ใช้ MySQL service ในการทดสอบฐานข้อมูล
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root  # รหัส root สำหรับ MySQL
          MYSQL_DATABASE: aquarium  # ชื่อฐานข้อมูลที่จะใช้
        ports:
          - 3306:3306  # พอร์ตที่ MySQL จะฟัง

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # ดึงโค้ดจาก GitHub

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # ติดตั้ง PHP
        with:
          php-version: '8.1'  # ใช้ PHP 8.1

      - name: Install dependencies
        run: composer install  # ติดตั้ง dependency ที่ระบุใน composer.json

      - name: Set up database
        run: |
          # ตั้งค่าฐานข้อมูล MySQL
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE aquarium;"

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit tests  # รันทดสอบ PHPUnit ที่อยู่ในโฟลเดอร์ tests/
