name: Run PHP Tests with PHPUnit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: aquarium
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, bcmath, mysql

      - name: Install dependencies
        run: composer install

      # ติดตั้ง wait-for-it
      - name: Install wait-for-it
        run: |
          curl -sSLo wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh

      # รอจนกว่า MySQL จะพร้อมใช้งาน
      - name: Wait for MySQL to be ready
        run: ./wait-for-it.sh 127.0.0.1:3306 --timeout=30 --strict -- echo "MySQL is up!"

      - name: Set up database
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS aquarium;"

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml
